[package]
name = "botimint"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
serenity = { version = "0.11.5", default-features = false, features = [
    "client",
    "gateway",
    "rustls_backend",
    "model",
] }
tokio = { version = "1.26.0", features = ["full"] }
tracing = "0.1.37"
reqwest = { version = "0.11.22", features = ["json"] }
serde = "1.0.190"
dotenv = "0.15.0"
config = "0.13.3"
tracing-subscriber = "0.3.17"
cln-rpc = "0.1.6"
